hi:
    echo "Hi there!"

test day part:
    cargo test --bin {{day}}_{{part}}

create day:
    cargo generate --path ./daily-template --name {{day}}

get-input day:
    ./scripts/get_input.rs --day {{day}} --current-working-dir {{justfile_directory()}}
